# Model arguments
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: False

# Data training arguments

chat_template:  "{% for message in messages %}\n{ '\nHuman: ' + message['goal'] +  eos_token }\n{ '\n\nAssistant: '  + message['code'] +  eos_token  }\n{% endfor %}\n{% if add_generation_prompt %}\n{{ '\n\nAssistant: ' }}\n{% endif %}"
dataset_mixer:
  rvind2508/Appian_PostProcessed1.2_Split: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: mistral-7b-sft-full
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 3 
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 24000
max_steps: -1
num_train_epochs: 3
output_dir: data/full-fintuned-mistral-7b
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: False
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: "epoch"
save_steps: 1
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
